artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: "https://github.com/Abdulbazid/text-summarizer-project/raw/main/summarizer-data.zip"
    local_data_files: artifacts/data_ingestion/data.zip
    unzip.dir: artifacts/data_ingestion